### ISSUE TITLE
rcon.connect() should return the TCP socket

### ISSUE THREAD

**Issue by pinuke** [electricessence/rcon-ts#2]
the net.socket returned from net.createConnection() contains properties with useful connection information like local/remote ip address and other details.

**Comment by electricessence** [comment]
I don't expose the actual socket because of state.  The whole point of this connector is to be an abstract.
If you absolutely need to get to those values, you can forcably access the private `rconInstance._socket` property.

If you have a suggestion on how you'd like this changed, I'd happily entertain a PR.
